# Add admin locators
admin_xpath = "//li[1]//a[1]//span[1]"
add_xpath = "//button[normalize-space()='Add']"
user_dropdown = "(//div[@class='oxd-select-text-input'][normalize-space()='-- Select --'])[1]"
user_role_xpath = "//div[@role='option' and @class='oxd-select-option']/span[text()='Admin']"
employee_name = "//input[@placeholder='Type for hints...']"
employee_name_value = "//div[@class='oxd-autocomplete-option'][1]"
status_dropdown = "//body[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]"
status_enabled = "//span[normalize-space()='Enabled']"
status_disabled = "//span[normalize-space()='Disabled']"
admin_username_xpath = "(//input[@class='oxd-input oxd-input--active'])[2]"
admin_password_xpath = "(//input[@type='password'])[1]"
confirm_password = "(//input[@type='password'])[2]"
save_button = "//button[@type='submit']"
close_button = "//button[normalize-space()='Cancel']"
username_alert = "//span[text() = 'Already exists']"

# Admin panel - Search locators
user_xpath = "(//input[@class = 'oxd-input oxd-input--active'])[2]"
userrole_dropdown = "(//div[@class='oxd-select-text-input'][normalize-space()='-- Select --'])[1]"
userrole_option = "(//span[text() = 'Admin'])[2]"
search_employee = "//input[@placeholder = 'Type for hints...']"
search_employee_dropdown = "//div[@role= 'listbox']//child::div[1]"
status = "(//div[@class='oxd-select-text oxd-select-text--active'])[2]"
search_enabled = "//span[text() = 'Enabled']"
search_disabled = "//span[text() = 'Disabled']"
search_button = "//button[@type = 'submit']"
reset_button = "//button[normalize-space()='Reset']"
record_found = "(//span[@class='oxd-text oxd-text--span'])[1]"
record_found_1 = "//span[text()='(1) Record Found']"

# Delete User
delete_button = "//div[text() = '[deleteuser]']//parent::div//following-sibling::div//div//button//i[contains(@class,'oxd-icon bi-trash')]"
edit_button = "//div[text()='[adduser]']//parent::div//following-sibling::div//div//button//i[contains(@class, 'bi-pencil-fill')]"
yes_delete = "//button[normalize-space()='Yes, Delete']"
no_close = "//button[normalize-space()='No, Cancel']"

# Edit User
edit_userrole = "(//div[@class='oxd-select-text oxd-select-text--active'])[1]"
select_userrole1 = "//div[@role='listbox']//div[2]"
select_userrole2 = "//div[@role='listbox']//div[3]"
edit_status = "(//div[@class = 'oxd-select-text oxd-select-text--active'])[2]"
select_status1 = "(//div[@role = 'listbox'])//div[2]"
select_status2 = "(//div[@role = 'listbox'])//div[3]"
edit_employee_name = "//input[@placeholder='Type for hints...']"
edit_username = "//input[contains(@class,'oxd-input oxd-input--active')]//ancestor::div//label[text()='Username']/parent::div/following-sibling::div//input"
change_password = "(//i[@class = 'oxd-icon bi-check oxd-checkbox-input-icon'])"
edit_password = "(//input[@class = 'oxd-input oxd-input--focus'])"
edit_confirm_password = "(//input[@class = 'oxd-input oxd-input--active'])[3]"
edit_cancel = "//button[normalize-space()='Cancel']"
edit_save = "//button[normalize-space()='Save']"
change_password_checkbox = "//span[@class='oxd-checkbox-input oxd-checkbox-input--active --label-right oxd-checkbox-input']"
# edit_password = "//input[@class='oxd-input oxd-input--active']//ancestor::div//label[text()='Password']//parent::div//following-sibling::div//input"
# edit_confirmpassword = "//input[@class='oxd-input oxd-input--active']//ancestor::div//label[text()='Confirm Password']//parent::div//following-sibling::div//input"

# Profile Locator
profile_click = "//i[@class='oxd-icon bi-caret-down-fill oxd-userdropdown-icon']"
about = "//a[text()='About']"
about_window = "//div[@role='document']"
about_close = "//button[normalize-space()='×']"
